Add files via upload

diff --git a/.github/workflows/sing-box.yaml b/.github/workflows/sing-box.yaml
--- a/.github/workflows/sing-box.yaml
+++ b/.github/workflows/sing-box.yaml
@@ -6,27 +6,35 @@ on:
 
 jobs:
   collect_sing-box:
-    name: "Running main.sh"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-go@v5
-        with:
-          go-version: 'stable'
+      - name: Install Serenity
+        run: bash <(curl -fsSL https://sing-box.app/serenity/deb-install.sh)
 
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.x"
+      - name: Run Node Collection using Serenity
+        run: nohup serenity run -c .github/serenity.json &
 
-      - name: collect and reformat sing-box nodes
-        run: bash .github/sing-box.sh
+      - name: Collect final.json
+        run: sleep 10s; curl -fsSL http://127.0.0.1:8080/final | jq -Sc > final.json || echo "CURL FAILED!"
+
+      - name: Merging with Templates
+        run: bash .github/merge.sh
+
+      - name: Install Sing-box
+        run: bash <(curl -fsSL https://sing-box.app/deb-install.sh)
+
+      - name: Testing Outputs using Sing-box
+        run: for i in release/sing-box/*.json; do sing-box check -c ${i} && echo "${i} is OK!"; done
+
+      - name: Update Rule-Set Binaries
+        run: for i in direct.json block.json; do sing-box rule-set format -w ${i} && sing-box rule-set compile ${i}; done
 
       - name: Commit
         run: |
           git config --local user.email "actions@github.com"
           git config --local user.name "GitHub Actions"
-          rm -rf serenity sing-box
           git add -A
           git commit -m "Updated on: `date`" || echo "No changes to commit"
           git push
